# Generated by Django 3.1.3 on 2020-11-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='C:\\Users\\nicoleta.manea\\PycharmProjects\\revbynic\\revbynic\\reviews\\static\\uploads'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rev_text',
            field=models.CharField(max_length=5000),
        ),
    ]
